# Config files for remote testing

# Directories
DIR:
  DATASET: '/cephfs/datasets/iccv_pnp/messy-table-dataset/real_v9/training/'  #  path to your sim testing dataset

# Split files
SPLIT:
  VAL: '/cephfs/datasets/iccv_pnp/messy-table-dataset/real_v9/training_lists/all.txt'  # training lists of your sim dataset
  LEFT: '0128_irL_kuafuv2_half.png'
  RIGHT: '0128_irR_kuafuv2_half.png'
  DEPTHL: 'depthL.png'
  DEPTHR: 'depthR.png'
  META: 'meta.pkl'
  LABEL: 'irL_label_image.png'

# Configuration for testing on real dataset
REAL:
  DATASET_V9: '/cephfs/datasets/iccv_pnp/real_data_v9/'
  DATASET: '/cephfs/datasets/iccv_pnp/messy-table-dataset/real_data_v10/'  # path to your real testing dataset
  LEFT: '1024_irL_real.png'
  RIGHT: '1024_irR_real.png'
  PAD_WIDTH: 960
  PAD_HEIGHT: 544